#!/usr/bin/env python
#pre-receive

print "Neon pre-receive"

import sys
import subprocess
import os

(old, new, remote_ref) = sys.stdin.read().split()

debianRemote = False
proc = subprocess.Popen(['git','remote'],stdout=subprocess.PIPE)
for line in iter(proc.stdout.readline,''):
   if line.rstrip() == "debian":
      debianRemote = True

cwd = os.getcwd().rsplit('/')
repo = cwd[-1][:-4]
if repo == "gitolite-admin": # don't do anything for admin archive
   sys.exit(0)

if not debianRemote:
   print "setting up debian remote"
   subprocess.check_call(['git','remote', 'add', 'debian', 'jriddell-guest@git.debian.org:/git/pkg-kde/' + repo])
   subprocess.check_call(['git','fetch', 'debian'])

user = os.environ['GL_USER']

if not "neon" in remote_ref and not "debiangit" in user: #debiangit user can push to non-neon branches for sync
   print "Only neon branches can be pushed to neon git, rejecting"
   sys.exit(1)
